module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      spacing: {
        1: '2px',
        840: "840px",
      },
      gridTemplateColumns: {
        layout: "1fr 3fr",
        "layout-sm": "1fr",
      },
      gridTemplateRows: {
        "layout-sm": "auto",
      },
      maxWidth: {
        840: "840px",
      },
      colors: {
        dark: "#1F2128",
        white: "#FFFFFF",
        concrete: "#F3F3F3",
        alabaster: "#F9F9F9",
        silver: "#C6C6C6",
        violet: "#AD00FF",
        "silver-chalice": "#AAA9A9",
        slate: {
          100: "rgb(241 245 249)",
          400: "rgb(148 163 184)",
          500: "rgb(100 116 139)",
          700: "#334155",
        },
        "regent-gray": "#8793A6",
        turquoise: "#42E2B8",
        "cornflower": "#7B61FF",
        "blue-chalk": "#E5DFFF",
        crimson: "#EF233C",
        "pig-pink": "#FCD3D8",
        "athens-gray": "#F0F3F5",
        "cod-gray": "#1B1B1B",
        mercury: "#E5E5E5",
        "mountain-m": "#24CD72",
        "granny-apple": "#DEF8EA",
        "aqua-haze": "#EFF2F6",
        ecstasy: "#F6851B",
        "catskill-white": "#E8EFF3",
        mystic: "#EAEEF2",
        "black-squeeze": "#F7FAFC",
        "curious-blue": "#2A8FD8",
        "dusty-gray": "#969696",
        "sand": "#F4F4F4",
        "bright-sun": "#FCD139",
        porcelain: "#E6EAEC",
        iron: "#CFD5D9",
        casal: "#2B6B5A",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
